# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def Fibonacci(x):
    Z = [1,2]
    next_term = 0

    while next_term < x:
        next_term = Z[-1] + Z[-2]
        if next_term < x:
            Z.append(next_term)
    return Z

Fibonacci_x = Fibonacci(4000000)
even_terms = [n for n in Fibonacci_x if n%2 == 0]
sum_even_terms = sum(even_terms)
print(sum_even_terms)